### ISSUE TITLE
rpt integrate has no --help and fails when running without arguments

### ISSUE THREAD

**Issue by seebi** [SmartDataAnalytics/RdfProcessingToolkit#13]
ergo: I am not able to see whats is possible.

```
rpt integrate --help
Usage: rpt integrate [-h]
Sparql Integrate
  -h, --help
```

```
∴ rpt integrate
[ERROR] Application startup failed
java.lang.IllegalArgumentException: Args must not be null
	at org.springframework.util.Assert.notNull(Assert.java:134)
	at org.springframework.boot.DefaultApplicationArguments.<init>(DefaultApplicationArguments.java:41)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:294)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
	at org.aksw.sparql_integrate.cli.MainCliSparqlIntegrate.main(MainCliSparqlIntegrate.java:557)
	at org.aksw.rdf_processing_toolkit.cli.cmd.CmdSparqlIntegrateMain.run(CmdSparqlIntegrateMain.java:20)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at org.aksw.rdf_processing_toolkit.cli.main.MainCliRdfProcessingToolkit.main(MainCliRdfProcessingToolkit.java:16)
java.lang.RuntimeException: java.lang.IllegalArgumentException: Args must not be null
	at org.aksw.commons.util.exception.ExceptionUtils.rethrowUnless(ExceptionUtils.java:35)
	at org.aksw.commons.util.exception.ExceptionUtils.rethrowIfNotBrokenPipe(ExceptionUtils.java:14)
	at org.aksw.rdf_processing_toolkit.cli.main.MainCliRdfProcessingToolkit.lambda$main$0(MainCliRdfProcessingToolkit.java:13)
	at picocli.CommandLine.execute(CommandLine.java:2068)
	at org.aksw.rdf_processing_toolkit.cli.main.MainCliRdfProcessingToolkit.main(MainCliRdfProcessingToolkit.java:16)
Caused by: java.lang.IllegalArgumentException: Args must not be null
	at org.springframework.util.Assert.notNull(Assert.java:134)
	at org.springframework.boot.DefaultApplicationArguments.<init>(DefaultApplicationArguments.java:41)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:294)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
	at org.aksw.sparql_integrate.cli.MainCliSparqlIntegrate.main(MainCliSparqlIntegrate.java:557)
	at org.aksw.rdf_processing_toolkit.cli.cmd.CmdSparqlIntegrateMain.run(CmdSparqlIntegrateMain.java:20)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	... 1 more
```

**Comment by Aklakan** [comment]
sparql-integrate has been ported to picocli - will use limbo as the test bed see whether its still all compatible

**Comment by Aklakan** [comment]
```bash
sorttest sparql-integrate -h
Usage: sparql-integrate [-ahuv] [--flat] [--server] [--jq[=<jqDepth>]]
                        [-o=<outFormat>] [--port=<serverPort>] [--o=<outFile> |
                        --io=<inOutFile>] [<nonOptionArgs>...]
Run sequences of SPARQL queries and stream triples, quads and bindings
      [<nonOptionArgs>...]   Arguments
  -a, --algebra              Show Algebra
      --flat                 Suppress JSON arrays for single valued properties
  -h, --help
      --io=<inOutFile>       input/output file
      --jq[=<jqDepth>]       Enable jq mode
      --o=<outFile>          output file
  -o, --w, --out-format=<outFormat>
                             Output format
      --port=<serverPort>    Server port
      --server               Start a SPARQL server
  -u, --u                    Union default graph mode
  -v, --version
```
